export const PERMISSIONS = {
  DASHBOARD: {
    READ_DASHBOARD: "READ DASHBOARD",
    READ_DASHBOARD_ANALYTIC: "READ DASHBOARD ANALYTIC",
  },
  USERS: {
    READ_USERS: "READ USERS",
    CREATE_USERS: "CREATE USERS",
    UPDATE_USERS: "UPDATE USERS",
    DELETE_USERS: "DELETE USERS",
  },
  ROLES: {
    READ_ROLES: "READ ROLES",
    CREATE_ROLES: "CREATE ROLES",
    UPDATE_ROLES: "UPDATE ROLES",
    DELETE_ROLES: "DELETE ROLES",
  },
  PERMISSIONS: {
    READ_PERMISSIONS: "READ PERMISSIONS",
    CREATE_PERMISSIONS: "CREATE PERMISSIONS",
    UPDATE_PERMISSIONS: "UPDATE PERMISSIONS",
    DELETE_PERMISSIONS: "DELETE PERMISSIONS",
  },
  SESSION_TESTS: {
    READ_SESSION_TESTS: "READ SESSION TESTS",
    CREATE_SESSION_TESTS: "CREATE SESSION TESTS",
    UPDATE_SESSION_TESTS: "UPDATE SESSION TESTS",
    DELETE_SESSION_TESTS: "DELETE SESSION TESTS",
  },
  TESTS: {
    READ_TESTS: "READ TESTS",
    CREATE_TESTS: "CREATE TESTS",
    UPDATE_TESTS: "UPDATE TESTS",
    DELETE_TESTS: "DELETE TESTS",
  },
};
